/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package project-m36-0.7.0.0 */
#define VERSION_project_m36 "0.7.0.0"
#define MIN_VERSION_megaparsec(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  0 || \
  (major1) == 7 && (major2) == 0 && (minor) <= 5)

/* megaparsec-7.0.5 */
#define VERSION_megaparsec "7.0.5"
#define MIN_VERSION_megaparsec(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  0 || \
  (major1) == 7 && (major2) == 0 & (minor) <= 5)

/* package stm-containers-1.1.0.4 */
#define VERSION_stm_containers "1.1.0.4"
#define MIN_VERSION_stm_containers(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)

/* network-transport-tcp-0.6.0 */
#define VERSION_network_transport_tcp "0.6.0"
#define MIN_VERSION_network_transport_tcp(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 & (minor) <= 0)

/* Win32-2.5.1 */
#define VERSION_Win32 "2.5.1"
#define MIN_VERSION_Win32(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 & (minor) <= 1)


