#!/usr/bin/env bash
# vim: ft=sh sw=2 et

set -euo pipefail

test() {
  TMP_FILE=$(mktemp)
  ldd $(jq --raw-output '.[0].result.exe_path' $($SNACK build)) &> $TMP_FILE
  diff golden $TMP_FILE
  rm $TMP_FILE 
}

SNACK="snack" test
